# Generated by Django 2.2.6 on 2019-10-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='published',
            field=models.BooleanField(),
        ),
    ]
