# Generated by Django 2.2.8 on 2020-01-18 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_squashed_0040_auto_20200117_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='project',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='thingsupport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='timesupport',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='timesupport',
            name='necessity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supports', to='projects.TimeNecessity'),
        ),
        migrations.AlterField(
            model_name='timesupport',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='timesupport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='timesupport',
            name='start_date',
            field=models.DateField(),
        ),
    ]
