# Generated by Django 2.2.6 on 2019-10-21 15:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_squashed_0002_auto_20191021_0606'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('edited_at', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=100)),
                ('bulstat', models.DecimalField(blank=True, decimal_places=0, max_digits=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HorodeyaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('edited_at', models.DateTimeField(editable=False)),
                ('bal', models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(100)])),
                ('legal_entity', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projects.LegalEntity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='legal_entity',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.LegalEntity'),
        ),
    ]
