# Generated by Django 2.2.6 on 2019-10-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20191027_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='legal_entity',
        ),
        migrations.AddField(
            model_name='user',
            name='legal_entites',
            field=models.ManyToManyField(to='projects.LegalEntity'),
        ),
    ]
