# Generated by Django 2.2.8 on 2020-01-28 10:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import rules.contrib.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200118_0641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('bulstat', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=20)),
                ('payment', models.TextField()),
                ('bal', models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(100)])),
            ],
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='project',
            name='legal_entity',
        ),
        migrations.RemoveField(
            model_name='user',
            name='legal_entities',
        ),
        migrations.DeleteModel(
            name='LegalEntity',
        ),
        migrations.AddField(
            model_name='community',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='community',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Community'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='communities',
            field=models.ManyToManyField(to='projects.Community'),
        ),
    ]
