# Generated by Django 2.2.6 on 2019-10-28 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20191028_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='admin',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
