# Generated by Django 2.2.8 on 2020-02-07 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0011_auto_20190223_2138'),
        ('projects', '0003_auto_20200130_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photologue.Photo'),
        ),
    ]
