# Generated by Django 2.2.8 on 2020-02-07 15:11

from django.db import migrations, models
import rules.contrib.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_community_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('text', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('CharField', 'CharField'), ('TextField', 'TextField')], max_length=20)),
                ('required', models.BooleanField(default=True)),
            ],
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='timenecessity',
            name='questions',
            field=models.ManyToManyField(to='projects.Question'),
        ),
    ]
