# Generated by Django 2.2.6 on 2019-10-28 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_legalentity_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='legal_entites',
            new_name='legal_entities',
        ),
    ]
