# Generated by Django 2.2.8 on 2020-02-08 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import rules.contrib.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200207_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timenecessity',
            name='questions',
        ),
        migrations.AddField(
            model_name='project',
            name='volunteer_questions',
            field=models.ManyToManyField(to='projects.Question'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('review', 'review'), ('delivered', 'delivered'), ('accepted', 'accepted'), ('declined', 'declined'), ('expired', 'expired')], default='review', max_length=20)),
                ('status_since', models.DateTimeField(default=django.utils.timezone.now)),
                ('answer', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.Project')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.Question')),
                ('time_support', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.TimeSupport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('time_support', 'question')},
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
