# Generated by Django 2.2.8 on 2020-02-08 06:24

from django.db import migrations, models
import django.db.models.deletion
import rules.contrib.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200208_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPrototype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('text', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('CharField', 'CharField'), ('TextField', 'TextField')], max_length=20)),
            ],
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
        migrations.AddField(
            model_name='question',
            name='prototype',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='projects.QuestionPrototype'),
            preserve_default=False,
        ),
    ]
