# Generated by Django 2.2.6 on 2019-10-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20191031_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='thumbs_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='thumbs_up',
            field=models.IntegerField(default=0),
        ),
    ]
