# Generated by Django 2.2.8 on 2020-02-08 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200208_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='volunteer_questions',
        ),
        migrations.AddField(
            model_name='question',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='projects.Project'),
            preserve_default=False,
        ),
    ]
