# Generated by Django 2.2.6 on 2019-10-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20191031_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='thumbs_down',
        ),
        migrations.RemoveField(
            model_name='report',
            name='thumbs_up',
        ),
        migrations.AddField(
            model_name='report',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
