# Generated by Django 2.2.8 on 2020-02-08 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200208_0630'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('prototype', 'project')},
        ),
    ]
