# Generated by Django 2.2.8 on 2020-02-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('projects', '0011_auto_20200209_1840'), ('projects', '0012_auto_20200209_1845')]

    dependencies = [
        ('projects', '0010_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionprototype',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionprototype',
            name='text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='questionprototype',
            name='type',
            field=models.CharField(choices=[('CharField', 'CharField'), ('TextField', 'TextField'), ('FileField', 'FileField'), ('RadioSelect', 'RadioSelect')], max_length=20),
        ),
        migrations.AlterField(
            model_name='questionprototype',
            name='text',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
