# Generated by Django 2.2.6 on 2019-11-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_moneysupport_timesupport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneysupport',
            name='accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moneysupport',
            name='delivered',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesupport',
            name='accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesupport',
            name='delivered',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
