# Generated by Django 2.2.6 on 2019-11-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20191101_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneysupport',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moneysupport',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesupport',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesupport',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
