# Generated by Django 2.2.6 on 2019-11-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20191101_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='leva_needed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
