# Generated by Django 2.2.8 on 2020-02-17 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20200212_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='payment',
        ),
        migrations.AddField(
            model_name='community',
            name='iban',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='revolut_phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='moneysupport',
            name='anonymous',
            field=models.BooleanField(default=False, help_text='Check if you want your name to be hidden', verbose_name='I wish to remain anonymous'),
        ),
        migrations.AddField(
            model_name='moneysupport',
            name='payment_method',
            field=models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('Revolut', 'Revolut')], default='Bank Transfer', max_length=20, verbose_name='Choose a payment method'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='community',
            name='phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='moneysupport',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Do you have a comment'),
        ),
        migrations.AlterField(
            model_name='moneysupport',
            name='leva',
            field=models.FloatField(verbose_name='How much do you wish to donate'),
        ),
        migrations.AlterField(
            model_name='moneysupport',
            name='necessity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='money_supports', to='projects.ThingNecessity', verbose_name='Which necessity do you wish to donate to'),
        ),
        migrations.AlterField(
            model_name='thingsupport',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Do you have a comment'),
        ),
        migrations.AlterField(
            model_name='timesupport',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Do you have a comment'),
        ),
    ]
