# Generated by Django 2.2.6 on 2019-11-01 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_leva_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bal',
            field=models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
