# Generated by Django 2.2.8 on 2020-02-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('projects', '0015_auto_20200218_0753'), ('projects', '0016_community_bank_account_bank_code')]

    dependencies = [
        ('projects', '0014_auto_20200217_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='iban',
        ),
        migrations.AddField(
            model_name='community',
            name='bank_account_iban',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='moneysupport',
            name='payment_method',
            field=models.CharField(choices=[('BankTransfer', 'Bank Transfer'), ('Revolut', 'Revolut')], default='Unspecified', max_length=20, verbose_name='Choose a payment method'),
        ),
        migrations.AddField(
            model_name='community',
            name='bank_account_bank_code',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
    ]
