# Generated by Django 2.2.6 on 2019-11-02 10:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20191102_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesupport',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 2, 10, 25, 39, 133270, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timesupport',
            name='note',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timesupport',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 2, 10, 25, 58, 289193, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
