# Generated by Django 2.2.8 on 2020-02-29 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_remove_project_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photologue.Photo'),
        ),
    ]
