# Generated by Django 2.2.8 on 2020-04-13 12:57

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import rules.contrib.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20200229_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonatorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('phone', models.CharField(max_length=20)),
                ('citizenship', django_countries.fields.CountryField(max_length=30)),
                ('domicile', django_countries.fields.CountryField(max_length=30)),
                ('postAddress', models.CharField(max_length=20)),
                ('TIN', models.CharField(max_length=10)),
                ('passportData', models.CharField(max_length=30)),
                ('birthdate', models.DateField()),
                ('placeOfBirth', models.CharField(max_length=30)),
                ('profession', models.CharField(max_length=30)),
                ('website', models.CharField(blank=True, max_length=30)),
            ],
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='user',
            name='donatorData',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.DonatorData'),
        ),
    ]
