# Generated by Django 2.2.6 on 2019-11-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_report_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='payment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
