# Generated by Django 2.2.6 on 2019-11-09 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_legalentity_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='bal',
        ),
        migrations.AddField(
            model_name='legalentity',
            name='bal',
            field=models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
