# Generated by Django 2.2.6 on 2019-12-02 16:37

from django.db import migrations, models
import django.db.models.deletion
import rules.contrib.models
import stream_django.activity


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20191109_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='report',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.Project'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('text', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.Project')),
            ],
            bases=(rules.contrib.models.RulesModelMixin, models.Model, stream_django.activity.Activity),
        ),
    ]
