# Generated by Django 2.2.8 on 2020-04-01 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20200321_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='mediaLink',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.MediaLink'),
        ),
    ]
