# Generated by Django 2.2.8 on 2020-04-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20200415_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='revolut_phone',
        ),
        migrations.AddField(
            model_name='community',
            name='DDORegistration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='community',
            name='activityType',
            field=models.CharField(choices=[('Creativity', ' Проекти от областта на науката или изкуството, които развиват градивната енергия на индивида и неговата сила за себе реализация.'), ('Education', 'Проекти, стъпили на принципа на висшата справедливост и въплащение на благородни мисли и желания в живота на човека, при което интуитивните и творческите му способности достигат нови нива.'), ('Art', ' Проекти в областта на културата, които събуждат естественото ни чувство за споделяне и придават финес на взаимоотношенията в обществото.'), ('Administration', 'Проекти, свързани със системи за създаване и прилагане на правила за истинно и честно социално взаимодействие. Механизми за разрешаване на спорове.'), ('Willpower', 'Проекти, които развиват смелост, устрем, воля за победа, воля за индивидуална и колективна изява, като спорт и туризъм.'), ('Health', 'Проекти, които следват естествения ритъм на човешкия организъм и са мост между Висшия и конкретния ум.'), ('Food', 'Проекти развиващи това, което най-пряко влияе върху нашите бит и ежедневие, допринасят за оцеляването и изхранването на обществото.')], default='Art', max_length=50),
        ),
        migrations.AddField(
            model_name='community',
            name='mission',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='numberOfSupporters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='community',
            name='previousExperience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='community',
            name='type',
            field=models.CharField(default='NGO', max_length=50),
        ),
        migrations.AddField(
            model_name='community',
            name='website',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
