# Generated by Django 2.2.8 on 2020-04-03 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20200401_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneysupport',
            name='user',
        ),
        migrations.RemoveField(
            model_name='thingsupport',
            name='user',
        ),
        migrations.AddField(
            model_name='moneysupport',
            name='donatorData',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.DonatorData'),
        ),
        migrations.AddField(
            model_name='moneysupport',
            name='legalEntityDonatorData',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.LegalEntityDonatorData'),
        ),
        migrations.AddField(
            model_name='thingsupport',
            name='donatorData',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.DonatorData'),
        ),
        migrations.AddField(
            model_name='thingsupport',
            name='legalEntityDonatorData',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.LegalEntityDonatorData'),
        ),
        migrations.AddField(
            model_name='timesupport',
            name='donatorData',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.DonatorData'),
        ),
        migrations.AddField(
            model_name='timesupport',
            name='legalEntityDonatorData',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.LegalEntityDonatorData'),
        ),
        migrations.AlterUniqueTogether(
            name='timesupport',
            unique_together={('necessity', 'donatorData')},
        ),
        migrations.RemoveField(
            model_name='timesupport',
            name='user',
        ),
    ]
