# Generated by Django 2.2.8 on 2020-04-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20200403_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='mission',
            field=models.TextField(default=None, null=True),
        ),
    ]
