# Generated by Django 2.2.8 on 2019-12-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20191208_1507'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoneyNecessity',
            new_name='ThingNecessity',
        ),
    ]
