# Generated by Django 2.2.8 on 2020-04-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_community_revolut_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='goal1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='goal2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='goal3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
