# Generated by Django 2.2.8 on 2020-05-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20200427_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date_tasks',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='report_period',
            field=models.CharField(choices=[('montly', 'montly'), ('twoweeks', 'twoweeks'), ('weekly', 'weekly')], default='weekly', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
