# Generated by Django 2.2.8 on 2019-12-08 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20191208_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='thingsupport',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='projects.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timesupport',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='projects.Project'),
            preserve_default=False,
        ),
    ]
