# Generated by Django 2.2.8 on 2020-05-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_user_second_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='facebook_page',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='bulstat',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True),
        ),
    ]
