# Generated by Django 2.2.8 on 2019-12-18 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20191208_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='budget_until',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='leva_needed',
        ),
    ]
