# Generated by Django 2.2.8 on 2019-12-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20191218_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='thingnecessity',
            name='fulfilled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timenecessity',
            name='fulfilled',
            field=models.IntegerField(default=0),
        ),
    ]
