# Generated by Django 2.2.8 on 2020-05-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20200505_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Education', 'Просвете и образование'), ('Creativity', 'Въображение и творчество'), ('Art', 'Изразяване и артистичност'), ('Finance', 'Администрация и финанси'), ('Willpower', 'Воля и утвърждаване'), ('Health', 'Святост и здравеопазване'), ('Food', 'Оцеляване и изранване')], default='Education', max_length=50),
        ),
    ]
