# Generated by Django 2.2.8 on 2020-01-07 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_auto_20191218_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneysupport',
            name='necessity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='money_supports', to='projects.ThingNecessity'),
        ),
        migrations.AlterField(
            model_name='moneysupport',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='thingsupport',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='timesupport',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
