# Generated by Django 2.2.8 on 2020-01-07 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_auto_20200107_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thingnecessity',
            name='fulfilled',
        ),
        migrations.RemoveField(
            model_name='timenecessity',
            name='fulfilled',
        ),
    ]
