# Generated by Django 2.2.8 on 2020-05-26 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20200525_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesupport',
            name='necessity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='projects.TimeNecessity'),
        ),
    ]
