# Generated by Django 2.2.8 on 2020-05-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_auto_20200526_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='slack_channel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slack_channel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='slack_channel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
