# Generated by Django 2.2.8 on 2020-01-13 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_project_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='primary_image',
        ),
    ]
