# Generated by Django 2.2.8 on 2020-06-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_auto_20200526_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
