# Generated by Django 2.2.8 on 2020-01-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_remove_project_primary_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='thingnecessity',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
