# Generated by Django 2.2.8 on 2020-01-14 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_thingnecessity_fulfilled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thingnecessity',
            name='fulfilled',
        ),
    ]
