# Generated by Django 2.2.8 on 2020-01-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_remove_thingnecessity_fulfilled'),
    ]

    operations = [
        migrations.AddField(
            model_name='thingsupport',
            name='from_money_supports',
            field=models.ManyToManyField(blank=True, to='projects.MoneySupport'),
        ),
    ]
