# Generated by Django 2.2.8 on 2020-01-17 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_auto_20200116_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneysupport',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='moneysupport',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='moneysupport',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='moneysupport',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='thingsupport',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='thingsupport',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='thingsupport',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='thingsupport',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='timesupport',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='timesupport',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='timesupport',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='timesupport',
            name='delivered_at',
        ),
        migrations.AddField(
            model_name='moneysupport',
            name='status',
            field=models.CharField(choices=[('r', 'review'), ('d', 'delivered'), ('a', 'accepted'), ('d', 'declined'), ('e', 'expired')], default='r', max_length=1),
        ),
        migrations.AddField(
            model_name='moneysupport',
            name='status_since',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='thingsupport',
            name='status',
            field=models.CharField(choices=[('r', 'review'), ('d', 'delivered'), ('a', 'accepted'), ('d', 'declined'), ('e', 'expired')], default='r', max_length=1),
        ),
        migrations.AddField(
            model_name='thingsupport',
            name='status_since',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='timesupport',
            name='status',
            field=models.CharField(choices=[('r', 'review'), ('d', 'delivered'), ('a', 'accepted'), ('d', 'declined'), ('e', 'expired')], default='r', max_length=1),
        ),
        migrations.AddField(
            model_name='timesupport',
            name='status_since',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
