# Generated by Django 2.2.8 on 2020-06-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_auto_20200616_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
    ]
