# Generated by Django 2.2.8 on 2020-06-25 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import rules.contrib.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_auto_20200616_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.CreateModel(
            name='EpayMoneySupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('supportType', models.CharField(max_length=30, null=True)),
                ('comment', models.TextField(blank=True, verbose_name='Do you have a comment')),
                ('status', models.CharField(choices=[('review', 'review'), ('delivered', 'delivered'), ('accepted', 'accepted'), ('declined', 'declined'), ('expired', 'expired')], default='review', max_length=20, verbose_name='status')),
                ('status_since', models.DateTimeField(default=django.utils.timezone.now, verbose_name='status_since')),
                ('amount', models.FloatField(verbose_name='How much do you wish to donate')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
