# Generated by Django 2.2.8 on 2020-01-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_auto_20200117_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneysupport',
            name='status',
            field=models.CharField(choices=[('r', 'review'), ('d', 'delivered'), ('a', 'accepted'), ('l', 'declined'), ('e', 'expired')], default='r', max_length=1),
        ),
        migrations.AlterField(
            model_name='thingsupport',
            name='status',
            field=models.CharField(choices=[('r', 'review'), ('d', 'delivered'), ('a', 'accepted'), ('l', 'declined'), ('e', 'expired')], default='r', max_length=1),
        ),
        migrations.AlterField(
            model_name='timesupport',
            name='status',
            field=models.CharField(choices=[('r', 'review'), ('d', 'delivered'), ('a', 'accepted'), ('l', 'declined'), ('e', 'expired')], default='r', max_length=1),
        ),
    ]
