# Generated by Django 2.2.8 on 2020-01-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_auto_20200117_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneysupport',
            name='status',
            field=models.CharField(choices=[('review', 'review'), ('delivered', 'delivered'), ('accepted', 'accepted'), ('declined', 'declined'), ('expired', 'expired')], default='review', max_length=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('business', 'business'), ('cause', 'cause')], max_length=1),
        ),
        migrations.AlterField(
            model_name='thingsupport',
            name='status',
            field=models.CharField(choices=[('review', 'review'), ('delivered', 'delivered'), ('accepted', 'accepted'), ('declined', 'declined'), ('expired', 'expired')], default='review', max_length=1),
        ),
        migrations.AlterField(
            model_name='timesupport',
            name='status',
            field=models.CharField(choices=[('review', 'review'), ('delivered', 'delivered'), ('accepted', 'accepted'), ('declined', 'declined'), ('expired', 'expired')], default='review', max_length=1),
        ),
    ]
