# Generated by Django 2.2.8 on 2020-07-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_auto_20200624_0613'),
        ('projects', '0038_auto_20200625_0817'),
    ]

    operations = [
    ]
