# Generated by Django 2.2.8 on 2020-01-30 10:34

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_squashed_0006_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('action', wagtail.core.blocks.StructBlock([('heading1', wagtail.core.blocks.CharBlock()), ('heading2', wagtail.core.blocks.CharBlock()), ('text1', wagtail.core.blocks.RichTextBlock()), ('text2', wagtail.core.blocks.RichTextBlock()), ('page1', wagtail.core.blocks.PageChooserBlock()), ('page2', wagtail.core.blocks.PageChooserBlock())], template='home/blocks/action.html')), ('action_register', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock())], template='home/blocks/action_register.html'))]),
        ),
    ]
