# Generated by Django 2.2.8 on 2020-02-29 08:02

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200130_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='body',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.TextBlock()), ('heroImage', wagtail.images.blocks.ImageChooserBlock()), ('person', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.TextBlock()), ('role', wagtail.core.blocks.TextBlock()), ('info', wagtail.core.blocks.TextBlock()), ('photo', wagtail.images.blocks.ImageChooserBlock()), ('order', wagtail.core.blocks.IntegerBlock())], template='home/blocks/person.html'))]),
        ),
    ]
