# Generated by Django 2.2.6 on 2019-11-09 14:04

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_termsandconditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('action', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.RichTextBlock()), ('page', wagtail.core.blocks.PageChooserBlock()), ('image_order', wagtail.core.blocks.IntegerBlock(default=0, max_value=1, min_value=0))], template='home/blocks/action.html')), ('action_register', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock())], template='home/blocks/action_register.html'))]),
        ),
    ]
