# Generated by Django 2.2.8 on 2020-01-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191109_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='type',
            field=models.CharField(choices=[('business', 'business'), ('cause', 'cause')], max_length=1),
        ),
    ]
