# Generated by Django 2.2.8 on 2020-01-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200117_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='type',
            field=models.CharField(choices=[('business', 'business'), ('cause', 'cause')], max_length=20),
        ),
    ]
